### ISSUE TITLE
torchvision=0.5.0 problem 

### ISSUE THREAD

**Issue by haiku75** [moboehland/thyroidclassification#4]

**Comment by haiku75** [comment]
could you please update the "requirements.yml" in the folder "segmentation".

Thankyou

**Comment by haiku1975** [comment]
I have the following updates, however, I am not sure if it will be compatible with the current project (to be tested).

Package | Latest Version

Python | 3.10.4
NumPy | 1.22.3
PyTorch | 1.13.0
PyTorch Lightning | 1.4.0
Pandas | 1.4.1
Albumentations | 1.1.0
TorchVision | 0.16.0
OpenCV | 4.5.5
Pillow | 9.1.0
Scikit-Learn | 1.0.2
Scikit-Image | 0.20.0
OpenPyXL | 3.1.0
PyTables | 3.8.0
XGBoost | 1.6.0
Skrebate | 0.62
MLXtend | 0.19.0
SciPy | 1.8.0
XLRD | 2.0.1
Joblib | 1.1.0
Seaborn | 0.12.1
TIFFfile | 2022.4.10

Best regards,
